//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs.Mysql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionString : DbContext
    {
        public ConnectionString()
            : base("name=ConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nomenclature> nomenclature { get; set; }
        public virtual DbSet<operations> operations { get; set; }
        public virtual DbSet<output_log> output_log { get; set; }
        public virtual DbSet<set_of_components> set_of_components { get; set; }
        public virtual DbSet<specification> specification { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<technolog_map> technolog_map { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
        public virtual DbSet<work_center> work_center { get; set; }
        public virtual DbSet<working_order> working_order { get; set; }
    }
}
