//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class output_log
    {
        public int id { get; set; }
        public Nullable<int> working_order_id { get; set; }
        public Nullable<int> work_center_id { get; set; }
        public Nullable<int> elapsed_time { get; set; }
    
        public virtual work_center work_center { get; set; }
        public virtual working_order working_order { get; set; }
    }
}
