//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id { get; set; }
        public int id_warehouse { get; set; }
        public int id_nomenclature { get; set; }
        public Nullable<int> value { get; set; }
    
        public virtual nomenclature nomenclature { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
