//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class technolog_map
    {
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<int> id_initial_operation { get; set; }
        public string description { get; set; }
    
        public virtual operations operations { get; set; }
    }
}
