//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs.Mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public working_order()
        {
            this.output_log = new HashSet<output_log>();
        }
    
        public int id { get; set; }
        public Nullable<int> nomenclature { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
        public Nullable<System.TimeSpan> start_date { get; set; }
        public Nullable<System.TimeSpan> end_date { get; set; }
        public Nullable<int> value { get; set; }
        public string description { get; set; }
    
        public virtual nomenclature nomenclature1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<output_log> output_log { get; set; }
        public virtual users users { get; set; }
    }
}
